#NEV_TEST> 24
### The external generator derives from GeneratorPythia8.
[GeneratorExternal]
fileName=/home/mdicosta/LocalTestsO2/OnTheFlyTracker/BeforeModifications/generator_pythia8_gaptriggered_hf.C
funcName=GeneratorPythia8GapTriggeredCharmAndBeauty(3000, -1.5, 1.5, -2, 2, {411, 431, 413, 421, 4122})

[GeneratorPythia8]
; config=/home/mdicosta/LocalTestsO2/OnTheFlyTracker/BeforeModifications/pythia8_charmhadronic_with_decays.cfg
config=/home/mdicosta/LocalTestsO2/OnTheFlyTracker/BeforeModifications/pythiaHardProcesses.cfg
includePartonEvent=true